name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build  -f ./windows/Dockerfile -t pyinstaller-windows .
      
      - name: Run Docker container
        run: docker run --rm  -v ${{ github.workspace }}\windows\dist\:C:\dist\ pyinstaller-windows powershell -Command "pyinstaller twi_gui.py --onedir --onefile --clean --distpath /dist --workpath /windows/build --specpath /windows"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-artifact
          path: ./windows/dist/main.exe
